steps:
  # Docker Build
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/layerdsample/react-image', '-f', './react/Dockerfile', './react' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/layerdsample/nest-image', '-f', './nest/Dockerfile', './nest' ]

  # Docker Push To Container Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: [ 'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/layerdsample/react-image' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/layerdsample/nest-image' ]
