apiVersion: apps/v1
kind: Deployment
metadata: 
  name: helloworld-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: asia-northeast1-docker.pkg.dev/gke-sample-327813/hello-repo/helloworld-gke:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
