apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: layerd-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layerd-sample
      tier: backend
  template:
    metadata:
      labels:
        app: layerd-sample
        tier: backend
    spec:
      containers:
        - name: nest
          tty: true
          image: asia-northeast1-docker.pkg.dev/gke-sample-327813/layerdsample/nest-image:latest
          env:
            - name: PRISMA_DATABASE_HOST
              value: 127.0.0.1:3306
            - name: PRISMA_DATABASE_NAME
              value: layerd_db_development
            - name: PRISMA_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: PRISMA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
          ports:
            - containerPort: 5000
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=gke-sample-327813:asia-northeast1:layerd-instance=tcp:3306",
                    # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
                    # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
                    # "-ip_address_types=PRIVATE",
                    "-credential_file=/secrets/cloudsql/cloudsql-account-key.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
