apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: layerd-sample
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: layerd-sample
    tier: frontend
