apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-follower
  labels:
    app: mysql
    role: follower
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        role: follower
        tier: backend
    spec:
      containers:
      - name: follower
        image: mysql:5.7
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
